//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetAtSchoolClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int Answer_ID { get; set; }
        public string Answer_Desc { get; set; }
        public Nullable<int> Question_ID { get; set; }
        public Nullable<int> isRichtig { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
